Repository Project-Skill-Tree/Skill-Tree-Discord-Bot, pull requests merged in 2022-03, with the labels that each got.

#22 Create Skill class (idk how this works)
  assets/badges/ReadingIII.png
  assets/characters/overseer.png
  commands/conf.js
  commands/skillTest.js
  config.js
  index.js
  objects/skill.js
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#28 Delete ReadingIII.png
  assets/badges/ReadingIII.png
Labels: enhancement

#30 added data folder to .gitignore
  .gitignore
Labels: bug, enhancement

#35 Copyright info update + Client ready in stat [old pr accidentally closed]
  LICENSE
  commands/stats.js
Labels: enhancement

#36 Add contribution docs
  README.md
  package-lock.json
  package.json
  yarn.lock
Labels: documentation

#41 Swipeable interface
  .env-example
  assets/badges/advanced.png
  assets/badges/elite.png
  assets/badges/eliteHex.png
  assets/icons/chest.png
  assets/icons/warning.png
  commands/challengeTest.js
  commands/item.js
  commands/mylevel.js
  commands/reboot.js
  commands/skillTest.js
  config.js
  events/guildMemberAdd.js
  events/messageCreate.js
  index.js
  modules/createSwipePanel.js
  modules/romanNumeralHelper.js
  objects/badge.js
  objects/challenge.js
  objects/item.js
  objects/skill.js
  objects/swipeable.js
  slash/leave.js
  slash/ping.js
  yarn.lock
Labels: enhancement

#45 Add .env-example
  .env-example
Labels: documentation, enhancement
