Repository Project-Skill-Tree/Skill-Tree-Discord-Bot, pull requests merged in 2022-04, with the labels that each got.

#50 Profile command
  assets/backgrounds/bg.png
  assets/badges/empty.png
  assets/characters/acolyte.png
  assets/characters/disciple.png
  assets/characters/gold_adonis.png
  assets/characters/maximus.png
  assets/characters/overseer.png
  assets/characters/purple_adonis.png
  assets/characters/red_spartan.png
  assets/characters/spartan.png
  assets/fonts/Akira.otf
  assets/icons/backpack.png
  assets/icons/chest.png
  assets/icons/warning.png
  commands/challengeTest.js
  commands/item.js
  commands/mylevel.js
  commands/profile.js
  commands/skillTest.js
  objects/XPHandler.js
  objects/badge.js
  objects/challenge.js
  objects/item.js
  objects/profile.js
  objects/rank.js
  objects/skill.js
Labels: enhancement

#51 Add task list
  commands/profile.js
  commands/skillTest.js
  commands/taskList.js
  modules/romanNumeralHelper.js
  objects/badge.js
  objects/profile.js
  objects/skill.js
  objects/task.js
  package-lock.json
  yarn.lock
Labels: enhancement

#52 Add a frequency formatter function
  commands/taskList.js
  modules/frequencyFormatter.js
  objects/skill.js
Labels: enhancement

#53 Autogenerated documentation
  .github/workflows/publish_to_docs.yml
  .gitignore
  README.md
  commands/profile.js
  commands/skillTest.js
  docs/jsdoc.json
  index.js
  modules/createSwipePanel.js
  objects/badge.js
  objects/item.js
  objects/profile.js
  objects/skill.js
  objects/swipeable.js
  package-lock.json
  package.json
  yarn.lock
Labels: documentation

#55 Add documentation site
  README.md
Labels: documentation

#54 Delete Yarn lockfile
  .env.example
  .github/workflows/publish_to_docs.yml
  commands/profile.js
  commands/taskList.js
  modules/APIHelper.js
  modules/UIHelper.js
  modules/XPHandler.js
  modules/createSwipePanel.js
  modules/frequencyFormatter.js
  modules/romanNumeralHelper.js
  objects/badge.js
  objects/challenge.js
  objects/item.js
  objects/profile.js
  yarn.lock
Labels: enhancement

#56 Documentation
  modules/APIHelper.js
  modules/UIHelper.js
  modules/XPHandler.js
  modules/createSwipePanel.js
  modules/frequencyFormatter.js
  modules/romanNumeralHelper.js
  objects/badge.js
  objects/swipeable.js
Labels: documentation

#60 Update publish_to_docs.yml
  .github/workflows/publish_to_docs.yml
Labels: bug
